package ca.bc.gov.nrs.frep.service.frep;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import ca.bc.gov.nrs.frep.dto.frep.GenerateMasterListRequest;
import ca.bc.gov.nrs.frep.repository.frep.MasterListCriteriaData;
import ca.bc.gov.nrs.frep.repository.frep.MasterListGenerationRow;
import ca.bc.gov.nrs.frep.repository.frep.MasterListRepository;
import ca.bc.gov.nrs.frep.security.LoggedUserHelper;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class MasterListAdminServiceTest {

  @Mock
  private MasterListRepository masterListRepository;

  @Mock
  private LoggedUserHelper loggedUserHelper;

  @InjectMocks
  private MasterListAdminService service;

  @Test
  void toResponseMapsLegacyCriteriaAndStats() {
    var data = new MasterListCriteriaData(
        "2024-03-31",
        "2023-04-01",
        5.0,
        12,
        "Generated by admin.",
        "N",
        List.of(new MasterListGenerationRow("DCK - Chilliwack Forest District", 38, 12, "N"))
    );

    var response = MasterListAdminService.toResponse("2024", data);

    assertEquals("2024", response.effectiveYear());
    assertTrue(response.generated());
    assertEquals("DCK", response.generationStats().get(0).orgUnitCode());
    assertEquals(12, response.generationStats().get(0).eligibleSites());
    assertEquals(38, response.generationStats().get(0).selectedSites());
  }

  @Test
  void getMasterListCriteriaLoadsFromRepository() {
    when(masterListRepository.getCriteria("2024")).thenReturn(new MasterListCriteriaData(
        "2024-03-31", "2023-04-01", 5.0, 12, "", "N", List.of()));

    var response = service.getMasterListCriteria("2024");

    assertEquals("2024", response.effectiveYear());
    assertFalse(response.generated());
  }

  @Test
  void generateMasterListCallsRepositoryAndReloadsCriteria() {
    when(loggedUserHelper.getLoggedUserId()).thenReturn("IDIR\\ADMIN");
    when(masterListRepository.getCriteria("2025")).thenReturn(new MasterListCriteriaData(
        "2025-03-31",
        "2024-04-01",
        5.0,
        12,
        "Generated.",
        "N",
        List.of(new MasterListGenerationRow("DCK - Chilliwack Forest District", 10, 8, "N"))
    ));

    var response = service.generateMasterList(new GenerateMasterListRequest(
        "2025", "2024-04-01", "2025-03-31", 5.0, 12, null, "Run generation"
    ));

    verify(masterListRepository).generate(
        eq("2025"),
        eq("2025-03-31"),
        eq("2024-04-01"),
        eq("5.0"),
        eq("12"),
        eq("Run generation"),
        eq("IDIR\\ADMIN")
    );
    assertTrue(response.generated());
  }

  @Test
  void generateRequiresYear() {
    assertThrows(IllegalArgumentException.class,
        () -> service.generateMasterList(
            new GenerateMasterListRequest("", null, null, null, null, null, null)));
  }
}
