package ca.bc.gov.nrs.frep.controller.v1;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import ca.bc.gov.nrs.frep.struct.v1.frep.MasterListAdminResponse;
import ca.bc.gov.nrs.frep.service.v1.frep.MasterListAdminService;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

@ExtendWith(MockitoExtension.class)
class MasterListAdminApiControllerTest {

  @Mock
  private MasterListAdminService masterListAdminService;

  private MockMvc mockMvc;

  @BeforeEach
  void setUp() {
    mockMvc = MockMvcBuilders
        .standaloneSetup(new MasterListAdminApiController(masterListAdminService))
        .build();
  }

  @Test
  void returnsCriteriaForYear() throws Exception {
    when(masterListAdminService.getMasterListCriteria("2024"))
        .thenReturn(new MasterListAdminResponse(
            "2024", "2023-04-01", "2024-03-31", 5.0, 12,
            "N", "Generated.", true, List.of()));

    mockMvc.perform(get("/api/v1/admin/master-list").param("effectiveYear", "2024"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.effectiveYear").value("2024"))
        .andExpect(jsonPath("$.generated").value(true));
  }

  @Test
  void badRequestWhenYearMissing() throws Exception {
    mockMvc.perform(get("/api/v1/admin/master-list"))
        .andExpect(status().isBadRequest());
  }

  @Test
  void generateRunsService() throws Exception {
    when(masterListAdminService.generateMasterList(any()))
        .thenReturn(new MasterListAdminResponse(
            "2025", "2024-04-01", "2025-03-31", 5.0, 12,
            "N", "Generated by stub.", true, List.of()));

    mockMvc.perform(post("/api/v1/admin/master-list/generate")
            .contentType(MediaType.APPLICATION_JSON)
            .content("{\"effectiveYear\":\"2025\"}"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.effectiveYear").value("2025"));
  }

  @Test
  void generateRejectsBlankYear() throws Exception {
    mockMvc.perform(post("/api/v1/admin/master-list/generate")
            .contentType(MediaType.APPLICATION_JSON)
            .content("{\"effectiveYear\":\"\"}"))
        .andExpect(status().isBadRequest());
  }
}
