package ca.bc.gov.nrs.frep.service.v1.frep;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import ca.bc.gov.nrs.frep.exception.ConflictFoundException;
import ca.bc.gov.nrs.frep.exception.StoredProcedureException;
import ca.bc.gov.nrs.frep.struct.v1.frep.GenerateMasterListRequest;
import ca.bc.gov.nrs.frep.repository.v1.bean.MasterListCriteriaData;
import ca.bc.gov.nrs.frep.repository.v1.bean.MasterListGenerationRow;
import ca.bc.gov.nrs.frep.repository.v1.MasterListRepository;
import ca.bc.gov.nrs.frep.security.LoggedUserHelper;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class MasterListAdminServiceTest {

  @Mock
  private MasterListRepository masterListRepository;

  @Mock
  private LoggedUserHelper loggedUserHelper;

  @InjectMocks
  private MasterListAdminService service;

  @Test
  void toResponseMapsLegacyCriteriaAndStats() {
    var data = new MasterListCriteriaData(
        "2024-03-31",
        "2023-04-01",
        5.0,
        12,
        "Generated by admin.",
        "N",
        List.of(new MasterListGenerationRow("43", "DCK - Chilliwack Forest District", 38, 12, "N"))
    );

    var response = MasterListAdminService.toResponse("2024", data);

    assertEquals("2024", response.effectiveYear());
    assertTrue(response.generated());
    assertEquals("43", response.generationStats().get(0).orgUnitNo());
    assertEquals("DCK", response.generationStats().get(0).orgUnitCode());
    assertEquals(12, response.generationStats().get(0).eligibleSites());
    assertEquals(38, response.generationStats().get(0).selectedSites());
    assertEquals("N", response.generationStats().get(0).resourceValueInd());
  }

  @Test
  void getMasterListCriteriaLoadsFromRepository() {
    when(masterListRepository.getCriteria("2024")).thenReturn(new MasterListCriteriaData(
        "2024-03-31", "2023-04-01", 5.0, 12, "", "N", List.of()));

    var response = service.getMasterListCriteria("2024");

    assertEquals("2024", response.effectiveYear());
    assertFalse(response.generated());
  }

  @Test
  void generateMasterListCallsRepositoryAndReloadsCriteria() {
    when(loggedUserHelper.getLoggedUserId()).thenReturn("IDIR\\ADMIN");
    when(masterListRepository.getCriteria("2025")).thenReturn(new MasterListCriteriaData(
        "2025-03-31",
        "2024-04-01",
        5.0,
        12,
        "Generated.",
        "N",
        List.of(new MasterListGenerationRow("43", "DCK - Chilliwack Forest District", 10, 8, "N"))
    ));

    var response = service.generateMasterList(new GenerateMasterListRequest(
        "2025", "2024-04-01", "2025-03-31", 5.0, 12, "Run generation"
    ));

    verify(masterListRepository).generate(
        eq("2025"),
        eq("2025-03-31"),
        eq("2024-04-01"),
        eq("5"),
        eq("12"),
        eq("Run generation"),
        eq("IDIR\\ADMIN")
    );
    assertTrue(response.generated());
  }

  @Test
  void generatePassesGrossAreaAsPlainNumberNotDoubleToString() {
    // Guards ORA-01722: whole numbers must lose the ".0" (5.0 -> "5"); fractions keep it (2.5 -> "2.5").
    when(loggedUserHelper.getLoggedUserId()).thenReturn("IDIR\\ADMIN");
    when(masterListRepository.getCriteria("2025")).thenReturn(new MasterListCriteriaData(
        "2025-03-31", "2024-04-01", 2.5, 12, "", "N", List.of()));

    service.generateMasterList(new GenerateMasterListRequest(
        "2025", "2024-04-01", "2025-03-31", 2.5, 12, "c"));

    verify(masterListRepository).generate(
        eq("2025"), eq("2025-03-31"), eq("2024-04-01"), eq("2.5"), eq("12"), eq("c"), eq("IDIR\\ADMIN"));
  }

  @Test
  void generateRequiresYear() {
    assertThrows(IllegalArgumentException.class,
        () -> service.generateMasterList(
            new GenerateMasterListRequest("", null, null, null, null, null)));
  }

  @Test
  void regenerateDistrictDelegatesAndReloads() {
    when(loggedUserHelper.getLoggedUserId()).thenReturn("IDIR\\ADMIN");
    when(masterListRepository.getCriteria("2025")).thenReturn(new MasterListCriteriaData(
        "2025-03-31", "2024-04-01", 5.0, 12, "", "N", List.of()));

    service.regenerateDistrict("2025", "43");

    verify(masterListRepository).regenerateDistrict("2025", "43", "IDIR\\ADMIN");
  }

  @Test
  void regenerateDistrictMapsExistingResourceToConflict() {
    when(loggedUserHelper.getLoggedUserId()).thenReturn("IDIR\\ADMIN");
    doThrow(new StoredProcedureException(
            "FREP_700_GEN_MASTER", "regenerate", "ca.bc.gov.mof.frep.regenerate.existingResource"))
        .when(masterListRepository).regenerateDistrict("2025", "43", "IDIR\\ADMIN");

    ConflictFoundException ex = assertThrows(
        ConflictFoundException.class, () -> service.regenerateDistrict("2025", "43"));
    assertTrue(ex.getMessage().toLowerCase().contains("regenerat"));
  }

  @Test
  void deleteListMapsResourcesAssociatedToConflict() {
    doThrow(new StoredProcedureException(
            "FREP_700_GEN_MASTER", "delete_list",
            "The MasterList has resources associated and can not be deleted."))
        .when(masterListRepository).deleteList("2025");

    ConflictFoundException ex = assertThrows(
        ConflictFoundException.class, () -> service.deleteList("2025"));
    assertTrue(ex.getMessage().toLowerCase().contains("deleted"));
  }

  @Test
  void regenerateDistrictRequiresYearAndOrgUnit() {
    assertThrows(IllegalArgumentException.class, () -> service.regenerateDistrict("2025", ""));
    assertThrows(IllegalArgumentException.class, () -> service.regenerateDistrict("", "43"));
  }

  @Test
  void saveCommentsDelegatesAndReloads() {
    when(loggedUserHelper.getLoggedUserId()).thenReturn("IDIR\\ADMIN");
    when(masterListRepository.getCriteria("2025")).thenReturn(new MasterListCriteriaData(
        "2025-03-31", "2024-04-01", 5.0, 12, "note", "N", List.of()));

    service.saveComments("2025", "note");

    verify(masterListRepository).saveComments("2025", "note", "IDIR\\ADMIN");
  }

  @Test
  void deleteListDelegatesAndReloads() {
    when(masterListRepository.getCriteria("2025")).thenReturn(new MasterListCriteriaData(
        "2025-03-31", "2024-04-01", 5.0, 12, "", "N", List.of()));

    service.deleteList("2025");

    verify(masterListRepository).deleteList("2025");
  }
}
