package ca.bc.gov.nrs.frep.service;

import ca.bc.gov.nrs.frep.dto.GenerateMasterListRequest;
import ca.bc.gov.nrs.frep.dto.MasterListAdminResponse;
import ca.bc.gov.nrs.frep.dto.MasterListGenerationStat;
import java.util.List;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Service;

/**
 * In-memory FREP700 data for local dev. Generation is a no-op that returns
 * deterministic stats.
 *
 * <p>Replaced in Phase 0.3 by JDBC calls to {@code FREP_700_GEN_MASTER}.
 */
@Service
public class StubMasterListAdminService implements MasterListAdminService {

  private static final List<MasterListGenerationStat> STATS_2024 = List.of(
      new MasterListGenerationStat("DCK", "Chilliwack Forest District", 38, 12),
      new MasterListGenerationStat("DKA", "Kamloops Forest District", 41, 12),
      new MasterListGenerationStat("DNI", "Nadina Forest District", 17, 9),
      new MasterListGenerationStat("DPC", "Prince George Forest District", 53, 12)
  );

  @Override
  public MasterListAdminResponse getMasterListCriteria(String effectiveYear) {
    boolean generated = "2024".equals(effectiveYear);
    return new MasterListAdminResponse(
        effectiveYear,
        "2023-04-01",
        "2024-03-31",
        5.0,
        12,
        "BIO,RIP,WAT,CHR",
        generated ? "Generated 2024-04-15 by IDIR\\ADMIN." : "",
        generated,
        generated ? STATS_2024 : List.of()
    );
  }

  @Override
  public MasterListAdminResponse generateMasterList(GenerateMasterListRequest request) {
    String year = request.effectiveYear();
    if (StringUtils.isBlank(year)) {
      throw new IllegalArgumentException("effectiveYear is required");
    }
    return new MasterListAdminResponse(
        year,
        defaultIfBlank(request.minHarvestCompleteDate(), "2023-04-01"),
        defaultIfBlank(request.maxHarvestCompleteDate(), "2024-03-31"),
        request.minOpeningGrossAreaHa() == null ? 5.0 : request.minOpeningGrossAreaHa(),
        request.maxSitesPerDistrict() == null ? 12 : request.maxSitesPerDistrict(),
        defaultIfBlank(request.resourceEvaluatedInd(), "BIO,RIP,WAT,CHR"),
        defaultIfBlank(request.comments(), "Generated by stub service."),
        true,
        STATS_2024
    );
  }

  private static String defaultIfBlank(String value, String fallback) {
    return StringUtils.isBlank(value) ? fallback : value;
  }
}
